services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: session_test
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always
